network:
  ethernets:
    enp0s3:
      dhcp4: false
      dhcp6: false
  # add configuration for bridge interface
  bridges:
    br0:
      interfaces: [enp0s3]
      dhcp4: false
      addresses: [10.0.55.reserved/24]
      macaddress: 08:00:27:4b:1d:45
      routes:
        - to: default
          via: 10.0.55.1
          metric: 100
      nameservers:
        addresses: [10.0.55.1]
      parameters:
        stp: false
      dhcp6: false
  version: 2